// ===================== i18n =====================
const LANG_NAMES = {de:'Deutsch', en:'English', fr:'Français', it:'Italiano', es:'Español'};
let LANG = localStorage.getItem('pawkin_lang') || ((navigator.language||'de').slice(0,2));
if(!LANG_NAMES[LANG]) LANG = 'en';
const DICTS = {
en:{
'Suchen':'Search','Buchungen':'Bookings','Chat':'Chat','Meine Tiere':'My Pets','Abmelden':'Log out','🐾 Sitter werden':'🐾 Become a sitter','🔁 Sitter':'🔁 Sitter','🔁 Besitzer':'🔁 Owner','0 % Provision':'0 % commission',
'Anmelden':'Sign in','Registrieren':'Sign up','Dein Name':'Your name','E-Mail':'Email','Passwort':'Password','Telefonnummer (optional, für Notfälle)':'Phone number (optional, for emergencies)','Ich möchte auch als Sitter betreuen':'I also want to offer pet sitting','Kostenlos registrieren':'Sign up for free','oder':'or','Weiter mit Google':'Continue with Google','Weiter mit Apple':'Continue with Apple','mind. 6 Zeichen':'min. 6 characters','du@example.com':'you@example.com','z. B. Thomas P.':'e.g. Thomas P.',
'Tierbetreuung, die nichts kostet.':'Pet care that costs nothing.','0 % Gebühren – Sitter behalten 100 %.':'0 % fees – sitters keep 100 %.',
'Finde liebevolle Betreuung – ohne Gebühren.':'Find loving pet care – with zero fees.','Geprüfte Sitter mit Quali-Level. Du zahlst keine Buchungsgebühr, Sitter behalten 100 %.':'Verified sitters with qualification levels. No booking fee, sitters keep 100 %.',
'Deine PLZ oder dein Ort (z. B. 1070 Wien)':'Your postcode or town (e.g. 1070 Vienna)','Umkreis:':'Radius:','egal':'any',
'🏠 Übernachtung':'🏠 Boarding','☀️ Tagesbetreuung':'☀️ Day care','🦮 Gassi-Runde':'🦮 Dog walk','🔑 Hausbesuch':'🔑 Drop-in visit','🤝 Kennenlernen':'🤝 Meet & greet','🐕 Hund':'🐕 Dog','🐈 Katze':'🐈 Cat',
'pro Nacht':'per night','pro Tag':'per day','pro Runde':'per walk','pro Besuch':'per visit','0 % Gebühren':'0 % fees','Keine Sitter in diesem Umkreis.':'No sitters within this radius.','Vergrößere den Radius oder ändere die Filter.':'Increase the radius or change the filters.','Keine Sitter für diese Auswahl.':'No sitters match this selection.',
'💊 Medikamentengabe':'💊 Medication handling','👴 Senioren-Erfahrung':'👴 Senior pet experience','🌿 Garten/Auslauf':'🌿 Garden / outdoor space','🐶 Verträgt andere Hunde':'🐶 Good with other dogs','⏱️ Max. 4 Std. allein':'⏱️ Max. 4 hrs alone','🤫 Geduld mit scheuen Tieren':'🤫 Patient with shy pets','🦮 Mind. 2 Gassirunden/Tag':'🦮 Min. 2 walks/day','🐈 Katzen-Erfahrung':'🐈 Cat experience',
'Level 1 · Identität & Basis-Check':'Level 1 · Identity & basic check','Level 2 · Erste-Hilfe-Kurs für Tiere':'Level 2 · Pet first-aid course','Level 3 · Zertifiziert für Medikamentengabe':'Level 3 · Certified for medication',
'‹ Zurück zur Suche':'‹ Back to search','Über mich':'About me','🎖️ Qualifikations-Level':'🎖️ Qualification level','Leistungen & Preise':'Services & prices','Kostenlos anfragen':'Request for free','🤝 Erst mal kennenlernen (gratis, ~30 Min)':'🤝 Meet & greet first (free, ~30 min)',
'Leistung':'Service','Zeitraum':'Dates','z. B. 12.8. – 14.8.':'e.g. Aug 12–14','Für welches Tier?':'For which pet?','Nachricht':'Message','Anfrage kostenlos senden':'Send request for free','Abbrechen':'Cancel','Sende…':'Sending…','Anfrage ist raus!':'Request sent!','Zu meinen Buchungen':'Go to my bookings','Weiter stöbern':'Keep browsing','Hallo! Wir suchen Betreuung für die angegebenen Tage. Das Tierprofil wird automatisch mitgeschickt.':'Hello! We are looking for care on the dates given. The pet profile is shared automatically.',
'Wunschtermin':'Preferred time','Kennenlernen anfragen':'Request meet & greet','z. B. Samstag Nachmittag oder 2.8. um 16:00':'e.g. Saturday afternoon or Aug 2, 4 pm',
'Meine Buchungen':'My Bookings','Anfrage gesendet':'Request sent','Bestätigt':'Confirmed','Abgelehnt':'Declined','Abgeschlossen':'Completed','Storniert':'Cancelled','💬 Chat':'💬 Chat','Stornieren':'Cancel booking','🔁 Erneut buchen':'🔁 Book again','Noch keine Buchungen.':'No bookings yet.',
'Nachrichten':'Messages','Noch keine Nachrichten.':'No messages yet.','‹ Alle Chats':'‹ All chats','Nachricht…':'Message…','Schreib die erste Nachricht 🐾':'Write the first message 🐾',
'➕ Tier anlegen':'➕ Add pet','Tier anlegen':'Add pet','Tier bearbeiten':'Edit pet','Name *':'Name *','Tierart *':'Species *','Hund':'Dog','Katze':'Cat','Rasse':'Breed','Alter / Gewicht':'Age / weight','z. B. 5 Jahre, 28 kg':'e.g. 5 years, 28 kg','Betreuungs-Bedürfnisse (steuern das Matching)':'Care needs (drive the matching)','Impfungen':'Vaccinations','Medikation':'Medication','Futter':'Food','Eigenheiten':'Quirks','Tierarzt':'Vet','Notfallkontakt':'Emergency contact','Mehr Details (alles optional):':'More details (all optional):','Anlegen':'Create','Speichern':'Save','Gespeichert':'Saved',
'🩺 Gesundheit':'🩺 Health','🍽️ Ernährung & Routine':'🍽️ Food & routine','🦮 Gassi & Draußen':'🦮 Walks & outdoors','🎾 Spiel & Beschäftigung':'🎾 Play & activities','🏠 Hausregeln & Erziehung':'🏠 House rules & training','🧠 Verhalten & Soziales':'🧠 Behaviour & social','🚨 Notfall-Vollmachten':'🚨 Emergency permissions',
'Allergien / Unverträglichkeiten':'Allergies / intolerances','Kastriert / sterilisiert':'Neutered / spayed','Chip-Nummer':'Chip number','Tierkrankenversicherung':'Pet health insurance','Fütterungszeiten':'Feeding times','Leckerlis erlaubt?':'Treats allowed?','Lieblings-Obst & -Gemüse':'Favourite fruit & veg','Verbotene Lebensmittel':'Forbidden foods','Alleinsein':'Being alone','Gassi-Zeiten':'Walk times','Worauf aufpassen?':'What to watch out for?','Leinenverhalten':'Leash behaviour','Freilauf erlaubt?':'Off-leash allowed?','Frisst vom Boden?':'Eats off the ground?','Wenn er etwas ins Maul nimmt':'If they pick something up','Lieblingsspiele':'Favourite games','So funktionieren sie':'How they work','Lieblingsspielzeug':'Favourite toys','Was beim Spielen gar nicht geht':'Play no-gos','Vom Tisch füttern?':'Feeding from the table?','Bett & Sofa':'Bed & sofa','Schlafplatz':'Sleeping place','Betteln & Hochspringen':'Begging & jumping up','Weitere Regeln':'Other rules','Verhalten mit Hunden':'Behaviour with dogs','Verhalten mit Katzen':'Behaviour with cats','Verhalten mit Kindern':'Behaviour with children','Ängste & Trigger':'Fears & triggers','Bekannte Kommandos (antippen)':'Known commands (tap)','Weitere Kommandos & Signale':'Other commands & signals','Tierarztbesuch erlaubt?':'Vet visit allowed?','Notfall-Budget':'Emergency budget','ausgefüllt':'filled in',
'Dein Sitter-Bereich':'Your sitter area','Anfragen, Klienten und Tierprofile – deine Preise, deine Regeln, 0 % Gebühren für immer.':'Requests, clients and pet profiles – your prices, your rules, 0 % fees forever.','⚙️ Mein Profil & Preise':'⚙️ My profile & prices','➕ Klienten einladen':'➕ Invite clients','📥 Anfragen & Buchungen':'📥 Requests & bookings','Noch keine Anfragen.':'No requests yet.','Teile dein Profil, um Klienten einzuladen!':'Share your profile to invite clients!','✓ Annehmen':'✓ Accept','Ablehnen':'Decline','🗂️ Tierprofil ansehen':'🗂️ View pet profile','Schließen':'Close',
'⚙️ Mein Sitter-Profil':'⚙️ My sitter profile','Über mich (sehen Besitzer in der Suche)':'About me (owners see this in search)','Stadt':'City','PLZ (für die Umkreis-Suche)':'Postcode (for radius search)','Ich betreue':'I care for','Hunde':'Dogs','Katzen':'Cats','Das biete ich an (wichtig fürs Matching)':'What I offer (drives the matching)',
'Nächste Impfauffrischung fällig (für Erinnerung)':'Next vaccination due (for reminder)','💊 Medikationsplan (mit Uhrzeiten – Sitter hakt jede Gabe ab)':'💊 Medication plan (with times – sitter checks off each dose)','➕ Medikament hinzufügen':'➕ Add medication','Sonstige Medikation / Hinweise':'Other medication / notes','Medikament':'Medication','Dosis':'Dose','Zeiten':'Times','📓 Logbuch & Pflege-Historie':'📓 Logbook & care history','📎 Dokument hochladen':'📎 Upload document','Noch keine Dokumente.':'No documents yet.','Öffnen':'Open','📓 Pflege':'📓 Care','💊 Medikamente heute':'💊 Today’s medication','✓ Jetzt geben':'✓ Give now','✓ gegeben':'✓ given','📝 Logbuch-Eintrag':'📝 Logbook entry','Notiz':'Note','Fütterung':'Feeding','Gassi':'Walk','Vorfall':'Incident','Eintrag speichern':'Save entry','Noch keine Einträge.':'No entries yet.',
'Standort gesetzt 📍':'Location set 📍','Suche Standort…':'Finding location…','Bitte PLZ oder Ort eingeben':'Please enter a postcode or town','Ort nicht gefunden – versuch z. B. „1070 Wien“':'Location not found – try e.g. “1070 Vienna”','Bitte einen Namen angeben':'Please enter a name','Kopiert 📋':'Copied 📋'
},
fr:{
'Suchen':'Recherche','Buchungen':'Réservations','Chat':'Messages','Meine Tiere':'Mes animaux','Abmelden':'Déconnexion','🐾 Sitter werden':'🐾 Devenir sitter','🔁 Besitzer':'🔁 Propriétaire','0 % Provision':'0 % de commission',
'Anmelden':'Connexion','Registrieren':'Inscription','Dein Name':'Votre nom','E-Mail':'E-mail','Passwort':'Mot de passe','Telefonnummer (optional, für Notfälle)':'Téléphone (facultatif, pour urgences)','Ich möchte auch als Sitter betreuen':'Je veux aussi proposer du pet-sitting','Kostenlos registrieren':'Inscription gratuite','oder':'ou','Weiter mit Google':'Continuer avec Google','Weiter mit Apple':'Continuer avec Apple','mind. 6 Zeichen':'min. 6 caractères',
'Tierbetreuung, die nichts kostet.':'La garde d’animaux qui ne coûte rien.','0 % Gebühren – Sitter behalten 100 %.':'0 % de frais – les sitters gardent 100 %.',
'Finde liebevolle Betreuung – ohne Gebühren.':'Trouvez une garde attentionnée – sans frais.','Geprüfte Sitter mit Quali-Level. Du zahlst keine Buchungsgebühr, Sitter behalten 100 %.':'Sitters vérifiés avec niveaux de qualification. Aucun frais de réservation, les sitters gardent 100 %.',
'Umkreis:':'Rayon :','egal':'peu importe','🏠 Übernachtung':'🏠 Hébergement','☀️ Tagesbetreuung':'☀️ Garderie de jour','🦮 Gassi-Runde':'🦮 Promenade','🔑 Hausbesuch':'🔑 Visite à domicile','🤝 Kennenlernen':'🤝 Rencontre','🐕 Hund':'🐕 Chien','🐈 Katze':'🐈 Chat',
'pro Nacht':'par nuit','pro Tag':'par jour','pro Runde':'par promenade','pro Besuch':'par visite','0 % Gebühren':'0 % de frais','Keine Sitter in diesem Umkreis.':'Aucun sitter dans ce rayon.',
'‹ Zurück zur Suche':'‹ Retour à la recherche','Über mich':'À propos de moi','🎖️ Qualifikations-Level':'🎖️ Niveau de qualification','Leistungen & Preise':'Services et tarifs','Kostenlos anfragen':'Demander gratuitement','🤝 Erst mal kennenlernen (gratis, ~30 Min)':'🤝 Faire connaissance d’abord (gratuit, ~30 min)',
'Leistung':'Service','Zeitraum':'Dates','Für welches Tier?':'Pour quel animal ?','Nachricht':'Message','Anfrage kostenlos senden':'Envoyer la demande gratuitement','Abbrechen':'Annuler','Anfrage ist raus!':'Demande envoyée !','Zu meinen Buchungen':'Voir mes réservations','Weiter stöbern':'Continuer à explorer',
'Meine Buchungen':'Mes réservations','Anfrage gesendet':'Demande envoyée','Bestätigt':'Confirmée','Abgelehnt':'Refusée','Abgeschlossen':'Terminée','Storniert':'Annulée','Stornieren':'Annuler','🔁 Erneut buchen':'🔁 Réserver à nouveau','Noch keine Buchungen.':'Pas encore de réservations.',
'Nachrichten':'Messages','Noch keine Nachrichten.':'Pas encore de messages.','‹ Alle Chats':'‹ Toutes les conversations','Nachricht…':'Message…',
'➕ Tier anlegen':'➕ Ajouter un animal','Tier anlegen':'Ajouter un animal','Tier bearbeiten':'Modifier l’animal','Rasse':'Race','Alter / Gewicht':'Âge / poids','Impfungen':'Vaccins','Medikation':'Médication','Futter':'Nourriture','Eigenheiten':'Particularités','Tierarzt':'Vétérinaire','Notfallkontakt':'Contact d’urgence','Mehr Details (alles optional):':'Plus de détails (tout est facultatif) :','Anlegen':'Créer','Speichern':'Enregistrer',
'🩺 Gesundheit':'🩺 Santé','🍽️ Ernährung & Routine':'🍽️ Alimentation et routine','🦮 Gassi & Draußen':'🦮 Promenades et extérieur','🎾 Spiel & Beschäftigung':'🎾 Jeux et activités','🏠 Hausregeln & Erziehung':'🏠 Règles de la maison','🧠 Verhalten & Soziales':'🧠 Comportement et social','🚨 Notfall-Vollmachten':'🚨 Autorisations d’urgence',
'Dein Sitter-Bereich':'Votre espace sitter','⚙️ Mein Profil & Preise':'⚙️ Mon profil et tarifs','➕ Klienten einladen':'➕ Inviter des clients','📥 Anfragen & Buchungen':'📥 Demandes et réservations','✓ Annehmen':'✓ Accepter','Ablehnen':'Refuser','Schließen':'Fermer','Stadt':'Ville','Ich betreue':'Je garde','Hunde':'Chiens','Katzen':'Chats'
},
it:{
'Suchen':'Cerca','Buchungen':'Prenotazioni','Chat':'Chat','Meine Tiere':'I miei animali','Abmelden':'Esci','🐾 Sitter werden':'🐾 Diventa sitter','🔁 Besitzer':'🔁 Proprietario','0 % Provision':'0 % di commissione',
'Anmelden':'Accedi','Registrieren':'Registrati','Dein Name':'Il tuo nome','E-Mail':'E-mail','Passwort':'Password','Telefonnummer (optional, für Notfälle)':'Telefono (facoltativo, per emergenze)','Ich möchte auch als Sitter betreuen':'Voglio anche fare il pet sitter','Kostenlos registrieren':'Registrati gratis','oder':'oppure','Weiter mit Google':'Continua con Google','Weiter mit Apple':'Continua con Apple','mind. 6 Zeichen':'min. 6 caratteri',
'Tierbetreuung, die nichts kostet.':'La cura degli animali che non costa nulla.','0 % Gebühren – Sitter behalten 100 %.':'0 % di commissioni – i sitter tengono il 100 %.',
'Finde liebevolle Betreuung – ohne Gebühren.':'Trova una cura amorevole – senza commissioni.','Geprüfte Sitter mit Quali-Level. Du zahlst keine Buchungsgebühr, Sitter behalten 100 %.':'Sitter verificati con livelli di qualifica. Nessuna commissione, i sitter tengono il 100 %.',
'Umkreis:':'Raggio:','egal':'qualsiasi','🏠 Übernachtung':'🏠 Pensione','☀️ Tagesbetreuung':'☀️ Asilo diurno','🦮 Gassi-Runde':'🦮 Passeggiata','🔑 Hausbesuch':'🔑 Visita a domicilio','🤝 Kennenlernen':'🤝 Conoscersi','🐕 Hund':'🐕 Cane','🐈 Katze':'🐈 Gatto',
'pro Nacht':'a notte','pro Tag':'al giorno','pro Runde':'a passeggiata','pro Besuch':'a visita','0 % Gebühren':'0 % commissioni','Keine Sitter in diesem Umkreis.':'Nessun sitter in questo raggio.',
'‹ Zurück zur Suche':'‹ Torna alla ricerca','Über mich':'Su di me','🎖️ Qualifikations-Level':'🎖️ Livello di qualifica','Leistungen & Preise':'Servizi e prezzi','Kostenlos anfragen':'Richiedi gratis','🤝 Erst mal kennenlernen (gratis, ~30 Min)':'🤝 Prima conosciamoci (gratis, ~30 min)',
'Leistung':'Servizio','Zeitraum':'Date','Für welches Tier?':'Per quale animale?','Nachricht':'Messaggio','Anfrage kostenlos senden':'Invia richiesta gratis','Abbrechen':'Annulla','Anfrage ist raus!':'Richiesta inviata!','Zu meinen Buchungen':'Alle mie prenotazioni','Weiter stöbern':'Continua a esplorare',
'Meine Buchungen':'Le mie prenotazioni','Anfrage gesendet':'Richiesta inviata','Bestätigt':'Confermata','Abgelehnt':'Rifiutata','Abgeschlossen':'Completata','Storniert':'Annullata','Stornieren':'Annulla','🔁 Erneut buchen':'🔁 Prenota di nuovo','Noch keine Buchungen.':'Ancora nessuna prenotazione.',
'Nachrichten':'Messaggi','Noch keine Nachrichten.':'Ancora nessun messaggio.','‹ Alle Chats':'‹ Tutte le chat','Nachricht…':'Messaggio…',
'➕ Tier anlegen':'➕ Aggiungi animale','Tier anlegen':'Aggiungi animale','Tier bearbeiten':'Modifica animale','Rasse':'Razza','Alter / Gewicht':'Età / peso','Impfungen':'Vaccinazioni','Medikation':'Farmaci','Futter':'Cibo','Eigenheiten':'Particolarità','Tierarzt':'Veterinario','Notfallkontakt':'Contatto di emergenza','Mehr Details (alles optional):':'Altri dettagli (tutto facoltativo):','Anlegen':'Crea','Speichern':'Salva',
'🩺 Gesundheit':'🩺 Salute','🍽️ Ernährung & Routine':'🍽️ Alimentazione e routine','🦮 Gassi & Draußen':'🦮 Passeggiate e all’aperto','🎾 Spiel & Beschäftigung':'🎾 Gioco e attività','🏠 Hausregeln & Erziehung':'🏠 Regole di casa','🧠 Verhalten & Soziales':'🧠 Comportamento e socialità','🚨 Notfall-Vollmachten':'🚨 Autorizzazioni di emergenza',
'Dein Sitter-Bereich':'La tua area sitter','⚙️ Mein Profil & Preise':'⚙️ Il mio profilo e prezzi','➕ Klienten einladen':'➕ Invita clienti','📥 Anfragen & Buchungen':'📥 Richieste e prenotazioni','✓ Annehmen':'✓ Accetta','Ablehnen':'Rifiuta','Schließen':'Chiudi','Stadt':'Città','Ich betreue':'Mi occupo di','Hunde':'Cani','Katzen':'Gatti'
},
es:{
'Suchen':'Buscar','Buchungen':'Reservas','Chat':'Chat','Meine Tiere':'Mis mascotas','Abmelden':'Cerrar sesión','🐾 Sitter werden':'🐾 Hazte cuidador','🔁 Besitzer':'🔁 Dueño','0 % Provision':'0 % de comisión',
'Anmelden':'Iniciar sesión','Registrieren':'Registrarse','Dein Name':'Tu nombre','E-Mail':'Correo','Passwort':'Contraseña','Telefonnummer (optional, für Notfälle)':'Teléfono (opcional, para emergencias)','Ich möchte auch als Sitter betreuen':'También quiero cuidar mascotas','Kostenlos registrieren':'Regístrate gratis','oder':'o','Weiter mit Google':'Continuar con Google','Weiter mit Apple':'Continuar con Apple','mind. 6 Zeichen':'mín. 6 caracteres',
'Tierbetreuung, die nichts kostet.':'Cuidado de mascotas que no cuesta nada.','0 % Gebühren – Sitter behalten 100 %.':'0 % de comisiones: los cuidadores se quedan el 100 %.',
'Finde liebevolle Betreuung – ohne Gebühren.':'Encuentra un cuidado cariñoso, sin comisiones.','Geprüfte Sitter mit Quali-Level. Du zahlst keine Buchungsgebühr, Sitter behalten 100 %.':'Cuidadores verificados con niveles de cualificación. Sin tarifas de reserva, se quedan el 100 %.',
'Umkreis:':'Radio:','egal':'da igual','🏠 Übernachtung':'🏠 Alojamiento','☀️ Tagesbetreuung':'☀️ Guardería de día','🦮 Gassi-Runde':'🦮 Paseo','🔑 Hausbesuch':'🔑 Visita a domicilio','🤝 Kennenlernen':'🤝 Conocerse','🐕 Hund':'🐕 Perro','🐈 Katze':'🐈 Gato',
'pro Nacht':'por noche','pro Tag':'por día','pro Runde':'por paseo','pro Besuch':'por visita','0 % Gebühren':'0 % comisiones','Keine Sitter in diesem Umkreis.':'No hay cuidadores en este radio.',
'‹ Zurück zur Suche':'‹ Volver a la búsqueda','Über mich':'Sobre mí','🎖️ Qualifikations-Level':'🎖️ Nivel de cualificación','Leistungen & Preise':'Servicios y precios','Kostenlos anfragen':'Solicitar gratis','🤝 Erst mal kennenlernen (gratis, ~30 Min)':'🤝 Conocerse primero (gratis, ~30 min)',
'Leistung':'Servicio','Zeitraum':'Fechas','Für welches Tier?':'¿Para qué mascota?','Nachricht':'Mensaje','Anfrage kostenlos senden':'Enviar solicitud gratis','Abbrechen':'Cancelar','Anfrage ist raus!':'¡Solicitud enviada!','Zu meinen Buchungen':'Ver mis reservas','Weiter stöbern':'Seguir explorando',
'Meine Buchungen':'Mis reservas','Anfrage gesendet':'Solicitud enviada','Bestätigt':'Confirmada','Abgelehnt':'Rechazada','Abgeschlossen':'Completada','Storniert':'Cancelada','Stornieren':'Cancelar','🔁 Erneut buchen':'🔁 Reservar de nuevo','Noch keine Buchungen.':'Aún no hay reservas.',
'Nachrichten':'Mensajes','Noch keine Nachrichten.':'Aún no hay mensajes.','‹ Alle Chats':'‹ Todos los chats','Nachricht…':'Mensaje…',
'➕ Tier anlegen':'➕ Añadir mascota','Tier anlegen':'Añadir mascota','Tier bearbeiten':'Editar mascota','Rasse':'Raza','Alter / Gewicht':'Edad / peso','Impfungen':'Vacunas','Medikation':'Medicación','Futter':'Comida','Eigenheiten':'Particularidades','Tierarzt':'Veterinario','Notfallkontakt':'Contacto de emergencia','Mehr Details (alles optional):':'Más detalles (todo opcional):','Anlegen':'Crear','Speichern':'Guardar',
'🩺 Gesundheit':'🩺 Salud','🍽️ Ernährung & Routine':'🍽️ Alimentación y rutina','🦮 Gassi & Draußen':'🦮 Paseos y exterior','🎾 Spiel & Beschäftigung':'🎾 Juego y actividades','🏠 Hausregeln & Erziehung':'🏠 Normas de casa','🧠 Verhalten & Soziales':'🧠 Comportamiento y social','🚨 Notfall-Vollmachten':'🚨 Permisos de emergencia',
'Dein Sitter-Bereich':'Tu área de cuidador','⚙️ Mein Profil & Preise':'⚙️ Mi perfil y precios','➕ Klienten einladen':'➕ Invitar clientes','📥 Anfragen & Buchungen':'📥 Solicitudes y reservas','✓ Annehmen':'✓ Aceptar','Ablehnen':'Rechazar','Schließen':'Cerrar','Stadt':'Ciudad','Ich betreue':'Cuido','Hunde':'Perros','Katzen':'Gatos'
}
};
const _tr = s => { if(LANG==='de') return s; const d=DICTS[LANG]; if(!d) return s; return d[s.trim()] !== undefined ? s.replace(s.trim(), d[s.trim()]) : s; };
function translateNode(root){
  if(LANG==='de') return;
  const d = DICTS[LANG]; if(!d) return;
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  let n;
  while(n = walker.nextNode()){
    const t = n.nodeValue.trim();
    if(t && d[t] !== undefined) n.nodeValue = n.nodeValue.replace(t, d[t]);
  }
  const els = root.querySelectorAll ? root.querySelectorAll('input[placeholder], textarea[placeholder]') : [];
  els.forEach(el=>{ const p = el.getAttribute('placeholder'); if(p && d[p] !== undefined) el.setAttribute('placeholder', d[p]); });
}
let _trPending = false;
const _observer = new MutationObserver(()=>{
  if(LANG==='de' || _trPending) return;
  _trPending = true;
  requestAnimationFrame(()=>{ _observer.disconnect(); translateNode(document.body); _observer.observe(document.body,{childList:true,subtree:true,characterData:true}); _trPending=false; });
});
window.openLangSheet = () => {
  $('sheet').innerHTML = '<h3>🌐 Sprache / Language</h3>'+
    Object.keys(LANG_NAMES).map(l=>`<button class="primary" style="margin-top:8px;${l===LANG?'':'background:var(--brand-light);color:var(--brand-dark)'}" onclick="localStorage.setItem('pawkin_lang','${l}');location.reload()">${LANG_NAMES[l]}${l===LANG?' ✓':''}</button>`).join('')+
    '<p style="font-size:11px;color:var(--muted);text-align:center;margin-top:12px;line-height:1.5">Weitere Sprachen folgen · More languages coming</p>'+
    '<button class="ghost" onclick="closeSheet()">OK</button>';
  $('ov').classList.add('show');
};
translateNode(document.body);
_observer.observe(document.body,{childList:true,subtree:true,characterData:true});
// ===================== /i18n =====================
